"""Minimal PDF report rendering for monitor runs (Phase 28.C).

PHASE_28_PLAN.md §10 (D10-C) calls for a PDF deliverable that mirrors
the Phase 17 ``vlabs-audit`` aesthetic. The full LaTeX pipeline at
``vlabs_audit.latex.render_pdf`` requires the ``tectonic`` binary
which isn't part of the API service runtime; for v0.0.1-alpha we emit
a self-contained, hand-built minimal PDF (PDF 1.4) that carries the
run summary as embedded text.

This is **deliberately minimal** — the goal is a downloadable
record that's a valid PDF a customer's email client / browser will
render, not a typeset report. A future iteration swaps in a richer
renderer (reportlab / weasyprint / tectonic) without changing the
column shape — `monitor_runs.pdf_storage_key` + `pdf_sha256` are the
only on-disk surface.
"""
from __future__ import annotations

from typing import Any


def _format_summary_lines(
    monitor_name: str,
    monitor_id: str,
    run_id: str,
    scheduled_at: str,
    finished_at: str,
    verdict: str,
    summary: dict[str, Any],
) -> list[str]:
    lines = [
        "Verifiable Labs Continuous Monitor Report",
        "",
        f"Monitor: {monitor_name}",
        f"Monitor ID: {monitor_id}",
        f"Run ID: {run_id}",
        f"Scheduled: {scheduled_at}",
        f"Finished:  {finished_at}",
        f"Verdict:   {verdict.upper()}",
        "",
        "Per-environment summary:",
    ]
    per_env = summary.get("per_env") or {}
    if not per_env:
        lines.append("  (no episodes recorded)")
    else:
        for env_id, stats in sorted(per_env.items()):
            n = stats.get("n", 0)
            mean = stats.get("mean_reward", 0.0)
            cov = stats.get("coverage", 0.0)
            lines.append(
                f"  {env_id}: n={n} mean_reward={mean:.4f} coverage={cov:.3f}"
            )
    lines.append("")
    overall_mean = summary.get("overall_mean_reward")
    overall_cov = summary.get("overall_coverage")
    if overall_mean is not None:
        lines.append(f"Overall mean reward: {overall_mean:.4f}")
    if overall_cov is not None:
        lines.append(f"Overall conformal coverage: {overall_cov:.3f}")
    lines.append("")
    lines.append("Generated by vlabs-api (Phase 28).")
    return lines


def _escape_pdf_text(text: str) -> str:
    """PDF text streams require backslash-escaping of these characters."""
    return (
        text.replace("\\", r"\\")
        .replace("(", r"\(")
        .replace(")", r"\)")
    )


def _build_text_content(lines: list[str]) -> bytes:
    """Build a PDF content stream emitting one Helvetica line per row."""
    parts: list[str] = ["BT", "/F1 11 Tf", "60 760 Td"]
    parts.append(f"({_escape_pdf_text(lines[0])}) Tj")
    parts.append("0 -22 Td")
    parts.append(f"({_escape_pdf_text(lines[1] if len(lines) > 1 else '')}) Tj")
    for line in lines[2:]:
        parts.append("0 -16 Td")
        parts.append(f"({_escape_pdf_text(line)}) Tj")
    parts.append("ET")
    return ("\n".join(parts) + "\n").encode("latin-1")


def render_monitor_pdf(
    *,
    monitor_name: str,
    monitor_id: str,
    run_id: str,
    scheduled_at: str,
    finished_at: str,
    verdict: str,
    summary: dict[str, Any],
) -> bytes:
    """Render a minimal, valid PDF byte stream for the monitor run.

    Output is a single-page PDF carrying the verdict + per-env summary
    table as Helvetica text. Returns the raw bytes, ready for upload
    via :mod:`vlabs_api.storage`.
    """
    lines = _format_summary_lines(
        monitor_name,
        monitor_id,
        run_id,
        scheduled_at,
        finished_at,
        verdict,
        summary,
    )
    content = _build_text_content(lines)

    objects: list[bytes] = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>"
        ),
        b"<< /Length " + str(len(content)).encode("latin-1") + b" >>\nstream\n"
        + content + b"endstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    body = b"%PDF-1.4\n%\xc4\xe5\xf2\xe5\xeb\xa7\xf3\xa0\xc4\xc4\xc6\n"
    offsets: list[int] = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(body))
        body += f"{i} 0 obj\n".encode("latin-1") + obj + b"\nendobj\n"

    xref_offset = len(body)
    body += f"xref\n0 {len(objects) + 1}\n".encode("latin-1")
    body += b"0000000000 65535 f \n"
    for off in offsets:
        body += f"{off:010d} 00000 n \n".encode("latin-1")
    body += (
        b"trailer\n"
        + f"<< /Size {len(objects) + 1} /Root 1 0 R >>\n".encode("latin-1")
        + b"startxref\n"
        + f"{xref_offset}\n".encode("latin-1")
        + b"%%EOF\n"
    )
    return body


__all__ = ["render_monitor_pdf"]
